# Generated by Django 4.2 on 2023-05-17 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajes',
            name='comentario',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='productos',
            name='categoria',
            field=models.CharField(choices=[('Sillas de oficina', 'Sillas de oficina'), ('Escritorios', 'Escritorios')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='productos',
            name='descripcion',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='productos',
            name='stock',
            field=models.CharField(choices=[('disponible', 'disponible'), ('no disponible', 'no disponible')], default='disponible', max_length=50),
        ),
        migrations.DeleteModel(
            name='Categorias',
        ),
    ]
